---
title: "Atlas des poissons d'eau douce de Bretagne"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: readable
    logo: www/faviconofb.png
    favicon: www/faviconofb.png

---



```{r setup, include = FALSE, echo = FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(mapview)
library(leafpop)
library(shiny)
library(sf)
library(leaflet)
source("gg_temp.R")
library(gt)
```


```{r}
load(file = "donnees_appli.RData")
```

```{r}
# initialisation
click_bv_esp <- reactive({
  DT::datatable(NULL)
})
```



Sidebar {.sidebar data-width=350}
=====================================

```{r}

# Slider années
sliderInput(
  inputId = "annees",
  label = "Années",
  min = min(pt_data$annee, na.rm = TRUE),
  max = max(pt_data$annee, na.rm = TRUE),
  value = c(
    min(pt_data$annee, na.rm = TRUE),
    max(pt_data$annee, na.rm = TRUE)
  ) ,
  round = 1,
  step = 1,
  sep = ""
)

# Menu sélection espèce
selectInput("espece",
            "Choisissez une espèce",
            choices = sort(unique(pt_data$esp_nom_commun)),
            selected = 1)

# Infos sur l'espèce sélectionnée
infos_esp <- reactive ({
  passerelle_taxo %>%
    filter(esp_nom_commun == input$espece) %>% 
    select(fiche_inpn1,
           lr_nationale,
           lr_regionale)
  })

# Statuts liste rouge
renderTable ({
  
  liste_rouge <- c("Nationale",
                   "Régionale")
  
  lr <- cbind(liste_rouge,
          infos_esp() %>% 
            select(-fiche_inpn1) %>% 
            t())
  
 colnames(lr) <- c("Liste rouge", "Statut")
 
 lr
  
})

# Lien vers la fiche INPN de l'espèce sélectionnée
renderUI ({
  HTML(
    infos_esp()$fiche_inpn1
  )
})

```



```{r}

# Construction objects reactive

# Objet couleurs 
couleurs <- c("#CC0000", "#FF99CC", "grey70", "#33FF66")

# Aggrégation des données au point
pt_data_aggr <- reactive({
  pt_data %>%
    filter(annee >= input$annees[1],
           annee <= input$annees[2],
           esp_nom_commun == input$espece) %>%
    group_by(code_coords,
             esp_nom_commun,
             localisation,
             ) %>%
    summarise(statut = max(statut)) %>%
    ungroup()
})

# Ajout de la géométrie au point
pt_map_data <- reactive({ 
  pt_geo %>% 
  left_join(pt_data_aggr()) %>% 
  mutate(
    statut = as.character(statut),
    statut = ifelse(is.na(statut),
                    "Non prospecté",
                    statut)) %>% 
    rename("Localisation" = localisation,
           "Espèce" = esp_nom_commun,
           "Statut" = statut
           )
  })

# Aggrégation des données au bv
bv_data_aggr <- reactive({
  bv_data %>% 
  filter(annee >= input$annees[1],
         annee <= input$annees[2],
         esp_nom_commun == input$espece) %>% 
  group_by(code_exutoire,
           code_espece,
           esp_nom_commun) %>%
    summarise(statut = max(statut)) %>% 
  ungroup()
  })

# Ajout de la géométrie au bv
bv_map_data <- reactive({
  bv_simp_geo %>% 
  left_join(bv_data_aggr()) %>% 
    group_by(code_exutoire, code_espece, esp_nom_commun) %>%
  mutate(statut = as.character(statut),
         statut = ifelse(is.na(statut),
                          "Non prospecté",
                          statut),
         esp_nom_commun = ifelse(is.na(esp_nom_commun),
                              input$espece,
                              esp_nom_commun)) %>% 
    rename("Nom du bassin" = toponyme,
           "Espèce" = esp_nom_commun,
           "Statut" = statut
           )
  })

# Construction des deux cartes (assemblées)
m1 <- reactive({
  (mapview(bv_map_data(),
        zcol = "Statut",
        layerId = bv_map_data()$code_exutoire, # identifiant pour pouvoir cliquer les polygones
        layer.name = input$espece,
        map.types = c("OpenStreetMap", "Esri.WorldImagery"),
        col.regions = couleurs,
        alpha.regions = 0.5,
          popup = popupTable(bv_map_data(),
                   zcol = c("Nom du bassin",
                            "Espèce",
                            "Statut"#,
                           # "Abondance"
                            ),
                   row.numbers=FALSE,
                   feature.id = FALSE)) +
    mapview(pt_map_data(),
          zcol = "Statut",
          col.region = couleurs,
     #     map.types = c("OpenStreetMap", "Esri.WorldImagery"),
          cex = ifelse(pt_map_data()$Statut == "Non prospecté", 2, 4),
          legend = FALSE,
          popup = popupTable(pt_map_data(),
                   zcol = c("Localisation",
                            "Espèce",
                            "Statut"#,
                          #  "Abondance"
                            ),
                   row.numbers = FALSE,
                   feature.id = FALSE)
          )) %>%
    .@map
  })

```



# Cartographie

Column {data-width=600}
-------------------------------------

<h4>
Cliquer sur un bassin pour afficher les espèces qui y sont recensées.
</h4>

```{r}
output$map <- leaflet::renderLeaflet({ m1() %>%
    leaflet::setView(lng = -3,
                     lat = 48.2,
                     zoom = 8)
  })


leafletOutput('map',
              height = 1000)  

```

```{r}
# Liste des espèces du bassin cliqué
click_bv_esp <- reactive ({  
  
  event <- input$map_shape_click
        print(event$id)
        
  req(event$id) # pour éviter un message d'erreur tant qu'aucun bassin n'a été cliqué
  
  bv_data %>%
    filter(code_exutoire == event$id,
           statut == "Présent") %>%
    left_join(passerelle_taxo) %>% 
    select(`Espèces présentes` = fiche_inpn2) %>% 
    distinct()
})

output$click_bv_esp <- renderDataTable({
  click_bv_esp()
}, escape = FALSE) # argument escape = FALSE pour que les liens soient cliquables

# nom du bassin cliqué
click_bv_nom <- reactive({
  
  event2 <- input$map_shape_click
       print(event2$id)
  
  req(event2$id)
  
  nom <- bv_simp_geo %>%
    sf::st_drop_geometry() %>% 
    filter(code_exutoire == event2$id) %>% 
    slice(1) %>% 
    pull(toponyme)
  
  nom
  
})


```

Column {data-width=150}
-------------------------------------

<h3>
```{r}
output$click_bv_nom <- renderText({
  click_bv_nom()
})

textOutput('click_bv_nom')
```
</h3>

```{r}
output$click_bv_esp3 <- renderDataTable({
  click_bv_esp()
}, escape = FALSE) # argument escape = FALSE pour que les liens soient cliquables
# Liste des espèces sur le BV sélectionné au clic

# if(exists("click_bv_esp3")) 
# {
dataTableOutput('click_bv_esp3')
#}
```



# Graphiques

```{r}

# =====================================
# CALCUL DATA POUR ETUDE




data_etude <- reactive ({
  pt_data %>%
    filter(esp_nom_commun == input$espece,
           statut == "Présent") %>%
    group_by(annee,
             statut) %>%
    summarise(n_presence = n())
})

g1 <- reactive ({
  gg_temp(data = data_etude(),
          var_x = annee,
          var_y = n_presence)
})

```

## Présences
```{r}
renderPlot({ g1() })

```



# Méthodologie

- Jeux de données  
- Création des fonctions  